Check date in release script

diff --git a/dev/scripts/release b/dev/scripts/release
--- a/dev/scripts/release
+++ b/dev/scripts/release
@@ -27,11 +27,18 @@ fi
 PACKAGE="$(cut -d/ -f2 <<<"$STATUS")"
 CHANGELOG="$(cut -b4- <<<"$STATUS")"
 VERSION="$(grep ^## "$CHANGELOG" | head -n1 | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+\S*' || true)"
+DATE="$(grep ^## "$CHANGELOG" | head -n1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}' || true)"
 TAG="@longlast/$PACKAGE@$VERSION"
 
 if [ -z "$VERSION" ]; then
     >&2 echo
     >&2 echo "Error: version in $CHANGELOG is malformed."
+    exit 1
+fi
+
+if [ "$DATE" != "$(date -I)" ]; then
+    >&2 echo
+    >&2 echo "Error: date in $CHANGELOG is wrong. Expected $(date -I)."
     exit 1
 fi
 
